# Generated by Django 4.2.3 on 2024-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktransaction',
            name='order_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
